FROM continuumio/miniconda3

WORKDIR /home/app

RUN apt-get update
RUN apt-get install nano unzip curl -y


RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
RUN unzip awscliv2.zip
RUN ./aws/install

COPY requirements.txt /dependencies/requirements.txt
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r /dependencies/requirements.txt

# Option 1
#CMD mlflow server -p $PORT \
#    --host 0.0.0.0 \
#    --backend-store-uri $BACKEND_STORE_URI \
#    --default-artifact-root $ARTIFACT_ROOT

# Option 2
CMD ["python", "getaround_rental_price_predictor_train.py"]
